# Generated by Django 5.2.9 on 2026-01-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_responsefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(blank=True, help_text='e.g., handbook, portal, form', max_length=100)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('undergraduate_local', 'Undergraduate Local'), ('undergraduate_international', 'Undergraduate International'), ('postgraduate', 'Postgraduate')], max_length=30, unique=True)),
                ('requirements', models.JSONField(default=dict, help_text='Admission requirements as JSON')),
                ('application_links', models.JSONField(default=dict, help_text='Links to application resources')),
                ('learning_approach', models.TextField(blank=True, help_text='Learning approach description')),
                ('language_requirements', models.JSONField(default=dict, help_text='Language proficiency requirements')),
                ('contact_info', models.JSONField(default=dict, help_text='Contact information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Information',
                'verbose_name_plural': 'Admission Information',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('focus', models.TextField(blank=True, help_text='Department focus area')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(blank=True, help_text='e.g., laboratory, research center, room', max_length=100)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('booking_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['facility_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('university', models.CharField(max_length=200)),
                ('established', models.CharField(blank=True, max_length=100)),
                ('dean', models.CharField(blank=True, max_length=200)),
                ('academic_staff_count', models.IntegerField(default=0)),
                ('administrative_staff_count', models.IntegerField(default=0)),
                ('address_street', models.CharField(blank=True, max_length=200)),
                ('address_postcode', models.CharField(blank=True, max_length=20)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=100)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Information',
                'verbose_name_plural': 'Faculty Information',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='KeyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('programme_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('focus_areas', models.JSONField(default=list, help_text='List of focus areas')),
                ('career_opportunities', models.JSONField(default=list, help_text='List of career opportunities')),
                ('learning_distribution', models.JSONField(default=dict, help_text='Coursework and practical percentages')),
                ('graduate_attributes', models.JSONField(default=list, help_text='List of graduate attributes')),
                ('programme_focus', models.TextField(blank=True, help_text='Focus description for postgraduate')),
                ('programme_format', models.CharField(blank=True, help_text='Coursework/Research/ODL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['programme_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TopManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('keywords', models.JSONField(default=list, help_text='Keywords for matching queries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(blank=True)),
                ('mission', models.JSONField(default=list, help_text='List of mission statements')),
                ('objectives', models.JSONField(default=list, help_text='List of objectives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vision & Mission',
                'verbose_name_plural': 'Vision & Mission',
            },
        ),
        migrations.RenameIndex(
            model_name='responsefeedback',
            new_name='django_app__message_2bc1e0_idx',
            old_name='django_app__message_f12345_idx',
        ),
        migrations.RenameIndex(
            model_name='responsefeedback',
            new_name='django_app__intent_314ac8_idx',
            old_name='django_app__intent_f_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='responsefeedback',
            new_name='django_app__session_343fc3_idx',
            old_name='django_app__session_xyz789_idx',
        ),
        migrations.RenameIndex(
            model_name='responsefeedback',
            new_name='django_app__created_901ac7_idx',
            old_name='django_app__created_def456_idx',
        ),
        migrations.AddIndex(
            model_name='courseinfo',
            index=models.Index(fields=['code'], name='django_app__code_14d92a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinfo',
            index=models.Index(fields=['category'], name='django_app__categor_0cd958_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type'], name='django_app__facilit_7b5ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category'], name='django_app__categor_4d135b_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['programme_type'], name='django_app__program_a26079_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['code'], name='django_app__code_b7e4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledata',
            index=models.Index(fields=['category'], name='django_app__categor_07e3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='topmanagement',
            index=models.Index(fields=['position'], name='django_app__positio_5ab801_idx'),
        ),
    ]
